spring:
  config:
    import: classpath:env.properties

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CreditPipeline
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${email_username}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true


management:
  endpoints:
    web:
      exposure:
        include: beans
server:
  port: 8081




