spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CreditPipeline
    username: postgres
    password: postgres


management:
  endpoints:
    web:
      exposure:
        include: beans